---
title: "DATA 607 Discussion 11 - Recommender Systems"
author: "Richie Rivera"
date: "2024-04-07"
output: html_document
---

Etsy is an online marketplace that attempts to connect producers of artisinal/handmade items and buyers. An attribute that Etsy has which I greatly respect is their online blog called (Code as Craft)[https://www.etsy.com/codeascraft/] where they write articles illustrating some of the interesting things that go on behind the scenes. One such of these articles is their (Personalized Recommendations at Etsy)[https://www.etsy.com/codeascraft/personalized-recommendations-at-etsy] which outlines a bit about how their personal recommendations system works at Etsy.

Before getting into the article, I can navigate to the homepage where I will find a few categories which are powered by a recommendation engine:

* "Because you viewed" - A list of items similar to what I may have seen on a previous journey to Etsy.
* "Similar to your favorites" - A list of items their recommendation system said are similar to my favorites.
* "Recommended Categories for you" - A list of categories of products which are recommended based on my activity.

I'll be focusing on "Recommended Categories for you" for my scenerio analysis. 

Clearly, the target users are perspective customers. People who will navigate to their website and potentially purchase something. The key goal here, ultimately is to generate a sale. Although the goal for one of these recommendation engines is much simpler and it is likely to incite the user to click. I believe that having the user click is more valuable because it allows the website to collect a bit more information on the user while having the user spend more time on the website, assumingly increasing their likelihood to purchase something. From their website, it's difficult to know exactly how they are performing this but I believe they are building similarity matrices which create generalized "profiles" for similar types of customer behaviors and then uses the learnings from those to inform their recommendation engine on which products to recommend next. An improvement which may not have been incorporated is to take the duration that a customer is on a page into consideration. I am supposing that there are behaviors that customers have while on the website which may be insightful in directing customer behavior. For example, some customers may not be on the website at all and other can be rigorously researching products. A recommendation for these two customers and a slew of other types can be more effective by modifying the approach to perhaps not even recommend anything and allow a customer to perform their research uninterrupted. By having this realtime information, there may be a way to better direct recommendations or to simply improve the customer journeys.

Now, I've completed reading their article where I can say that it seems like Etsy uses the favorites that users have and use some sort of matrix to store a users "affinity" to that specific item. With that, they are able to create scores for each user and item combination. There are a lot of methods that Etsy uses to optimize their results to something that they are interested in but ultimately at the end they are using approximating the nearest neighbors using their respective Euclidean distance from eachother. From there, they are then selecting items for recommendation.

The article does verify that they are not using some sort of user behavior and, now that I've seen how intelligent their design is in their recommendation engine, I wonder if that had already been considered.